app = "keeviqo-platform"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
